export const LOAD_USERS_START ="LOAD_USERS_START"
export const LOAD_USERS_ERROR ="LOAD_USERS_ERROR"
export const LOAD_USERS_SUCCESS ="LOAD_USERS_SUCCESS"


export const LOGIN_USERS_START ="LOGIN_USERS_START"
export const LOGIN_USERS_ERROR ="LOGIN_USERS_ERROR"
export const LOGIN_USERS_SUCCESS ="LOGIN_USERS_SUCCESS"

export const ADD_USER_START="ADD_USER_START"
export const ADD_USER_SUCCESS="ADD_USER_SUCCESS"
export const ADD_USER_ERROR="ADD_USER_ERROR"

export const DEL_USER_START="DEL_USER_START"
export const DEL_USER_SUCCESS="DEL_USER_SUCCESS"
export const DEL_USER_ERROR="DEL_USER_ERROR"

export const EDIT_USER_START="EDIT_USER_START"
export const EDIT_USER_SUCCESS="EDIT_USER_SUCCESS"
export const EDIT_USER_ERROR="EDIT_USER_ERROR"

export const UPLOAD_IMG_START="UPLOAD_IMG_START"
export const UPLOAD_IMG_SUCCESS="UPLOAD_IMG_SUCCESS"
export const UPLOAD_IMG_ERROR="UPLOAD_IMG_ERROR"

export const ADD_CHK_START="ADD_CHK_START"
export const ADD_CHK_SUCCESS="ADD_CHK_SUCCESS"
export const ADD_CHK_ERROR="ADD_CHK_ERROR"


//editor Add

export const ADD_EDI_START="ADD_EDI_START"
export const ADD_EDI_SUCCESS="ADD_EDI_SUCCESS"
export const ADD_EDI_ERROR="ADD_EDI_ERROR"

//get Editor
export const LOAD_EDI_START ="LOAD_EDI_START"
export const LOAD_EDI_ERROR ="LOAD_EDI_ERROR"
export const LOAD_EDI_SUCCESS ="LOAD_EDI_SUCCESS"



