export const LOAD_USERS_START ="LOAD_USERS_START"
export const LOAD_USERS_ERROR ="LOAD_USERS_ERROR"
export const LOAD_USERS_SUCCESS ="LOAD_USERS_SUCCESS"


export const LOGIN_USERS_START ="LOGIN_USERS_START"
export const LOGIN_USERS_ERROR ="LOGIN_USERS_ERROR"
export const LOGIN_USERS_SUCCESS ="LOGIN_USERS_SUCCESS"

export const ADD_USER_START="ADD_USER_START"
export const ADD_USER_SUCCESS="ADD_USER_SUCCESS"
export const ADD_USER_ERROR="ADD_USER_ERROR"

export const DEL_USER_START="DEL_USER_START"
export const DEL_USER_SUCCESS="DEL_USER_SUCCESS"
export const DEL_USER_ERROR="DEL_USER_ERROR"

export const EDIT_USER_START="EDIT_USER_START"
export const EDIT_USER_SUCCESS="EDIT_USER_SUCCESS"
export const EDIT_USER_ERROR="EDIT_USER_ERROR"


